export const UPDATE_GRAFIC = 'UPDATE_GRAFIC';
export const UPDATE_REFAREAS = 'UPDATE_REFAREAS';
export const UPDATE_REFAREALEFT = 'UPDATE_REFAREALEFT';
export const UPDATE_REFAREARIGHT = 'UPDATE_REFAREARIGHT';
export const UPDATE_DATA = 'UPDATE_DATA';